#!/usr/bin/env python3
import re,sys,os,shutil

e=re.compile(r"\s*constant\s*C_([A-Z_0-9]+)\s*:\s*integer\s*:=\s*([0-9]+?)\s*;$")

data=dict()

fields={
  "SELECTOR_BITS": "selectorBits",
  "INTERPOLATION_BITS": "interpolationBits",
  "SEGMENT_BITS": "segmentBits",
  "PLA_INTERCONNECTS":"plaInterconnects",
  "BASE_BITS": "base_bits",
  "INCLINE_BITS": "incline_bits",
  "INPUT_DECODER_DELAY": "delay_inputDecoder",
  "ADDRESS_TRANSLATOR_DELAY": "delay_addressTranslator",
  "INTERPOLATOR_DELAY": "delay_interpolator",
  "CONTROLLER_DELAY": "delay_controller",
  "INPUT_WORDS": "inputWords",
}

with open("lut_package.vhd","r") as f:
  for ln in f:
    m=e.match(ln.strip())
    if m:
      g=m.groups()
      data[g[0]]=int(g[1])

with open("default.arch","w") as f:
  for field in sorted(fields):
    f.write("%s = %s\n"%(fields[field],data[field]))

